export const ADD_BOOK = 'ADD_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const UPDATE_BOOK = 'UPDATE_BOOK'
export const SET_ITEMS = 'SET_ITEMS'
export const GET_ALL_BOOOKS= 'GET_ALL_BOOOKS'
